hide test exit code lines

diff --git a/.github/workflows/deploy-with-config.yml b/.github/workflows/deploy-with-config.yml
--- a/.github/workflows/deploy-with-config.yml
+++ b/.github/workflows/deploy-with-config.yml
@@ -867,16 +867,16 @@ jobs:
         run: |
           set -o pipefail
           PW_CHANNEL=chrome npx nx e2e e2e-${{ github.event.inputs['project-name'] }} --grep="live/" --skip-nx-cache --skipInstall --parallel=1 2>&1 | tee test_output.log
-          TEST_EXIT_CODE=$?
-          if [ $TEST_EXIT_CODE -ne 0 ]; then
-            echo "🔍 Test failed, analyzing output..."
-            if [ -f test_output.log ]; then
-              # Extract failed and flaky tests
-              FAILED_TESTS_LIST=$(grep -A20 "failed" test_output.log | grep -B20 "flaky" | sed '$d' | grep -o "[a-zA-Z0-9_-]*\.spec\.ts" | sort -u)
-              echo "💥 Broken tests: ${FAILED_TESTS_LIST:-Unknown}"
-            fi
-            exit $TEST_EXIT_CODE
-          fi
+          # TEST_EXIT_CODE=$?
+          # if [ $TEST_EXIT_CODE -ne 0 ]; then
+          #   echo "🔍 Test failed, analyzing output..."
+          #   if [ -f test_output.log ]; then
+          #     # Extract failed and flaky tests
+          #     FAILED_TESTS_LIST=$(grep -A20 "failed" test_output.log | grep -B20 "flaky" | sed '$d' | grep -o "[a-zA-Z0-9_-]*\.spec\.ts" | sort -u)
+          #     echo "💥 Broken tests: ${FAILED_TESTS_LIST:-Unknown}"
+          #   fi
+          #   exit $TEST_EXIT_CODE
+          # fi
 
       - name: Report the live test failure
         if: failure() && !cancelled()
